// lib/firebase_options.dart
//
// A tiny stub that satisfies `Firebase.initializeApp` for the unit test.
// In a production build you will replace this file with the one generated by
// `flutterfire configure`.  All fields can be empty strings – the test does not
// contact any Firebase service.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    // Optional fields (web, macOS) can be omitted.
  );
}
