// lib/firebase_options.dart
//
// This file is normally generated by `flutterfire configure`.
// For CI we only need a *valid* class with a static `currentPlatform`
// that returns a `FirebaseOptions` object.  All fields can be empty
// strings – Firebase.initializeApp will still succeed in a test
// environment.

import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  // The stub options – replace with real values in a production build.
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: '',
    appId: '',
    messagingSenderId: '',
    projectId: '',
    // Optional fields for web / macOS can be omitted.
  );
}
