// Flutter entry point
// lib/main.dart
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

// This file is generated by the FlutterFire CLI (`flutterfire configure`)
// – it contains the Firebase options for Android, iOS, web, etc.
import 'firebase_options.dart';

// App‑wide router (you already have this file in lib/routes/app_router.dart)
import 'routes/app_router.dart';

// Theme constants (core/constants/theme.dart)
import 'core/constants/theme.dart';

/// Entry‑point for **both** the real app and the widget test.
void main() async {
  // Needed because we call async code (Firebase) before `runApp`.
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase with the platform‑specific options.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Riverpod's ProviderScope gives the whole app access to providers.
  runApp(const ProviderScope(child: HouseBuddyApp()));
}

/// The widget that the test looks for (`HouseBuddyApp`).
class HouseBuddyApp extends ConsumerWidget {
  const HouseBuddyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp.router(
      // -----------------------------------------------------------------
      // Basic app metadata
      // -----------------------------------------------------------------
      title: 'HouseBuddy',
      debugShowCheckedModeBanner: false,

      // -----------------------------------------------------------------
      // Theme – you already defined a nice iOS‑style theme in
      // core/constants/theme.dart
      // -----------------------------------------------------------------
      theme: AppTheme.light,

      // -----------------------------------------------------------------
      // Router – all your screens (home, service list, booking flow, etc.)
      // are defined in lib/routes/app_router.dart
      // -----------------------------------------------------------------
      routerConfig: appRouter,
    );
  }
}
